### ISSUE TITLE
Reference Point

### ISSUE THREAD

**Issue by SMJMirza** [yumorishita/LiCSBAS#102]
Hi Everyone,

I used the LiCSBAS for several frames and read the comments of steps during the job. I found that the reference point will be changed from step 12 to 16 and it is finally selected automatically by the program. When I checked the selected reference point, I found it not very well in a stable location.

Could you please let me know how I can set the reference point manually and keep it unchanged during the job?

Sincerely,
Sayyed

**Comment by yumorishita** [comment]
You can manually set the reference point or area for the inverted time series result by -r or --ref_geo options in LiCSBAS_plot_ts.py, LiCSBAS_cum2flt.py, LiCSBAS_cum2vel.py, or LiCSBAS_cum2tstxt.py when you output the velocity or time series.

It does not degrade the quality of the result even if the automatically determined reference point during the processing exists in an unstable area because the reference point only for the final result matters. If you manually set a reference point which have no data or unwrapping errors in some interferograms during the processing (i.e., step12-16), you would get worse result. The automatically determined reference point has the lowest possibility of such problems and better than manually selected one.

**Comment by SMJMirza** [comment]
Thank you for your response. I did the post-processing for nine LiCSAR frames in Central Iran and got the results. In several frames, I checked the final reference point and found that it is located near to fault trace or inside the aquifer boundary. on the other hand, the coherency value of selected reference point is not the best one over the frame. So, I think that we can change it though the information from the area (fault traces, geological setting, and aquifers boundaries).

**Comment by yumorishita** [comment]
It seems that you did an appropriate reference selection in the post processing.

The manual setting of the reference point during the processing (step12-16) would not make significant difference in the SB inversion and result.

Please note that the highest coherence does not mean the lowest error possibility because coherent pixels can have unwrapping errors with respect to other areas if the coherent pixels are surrounded by decorrelated pixels. Since the automatic selection takes into account the coherent unwrapping errors, I think it is better.

**Comment by christianbignami** [comment]
If I correctly understand, the manual setting of the ref during PS allow to change the velocity map png, used for the visualization. This will facilitate the identification of the moving areas.
On step 1-3 of LiCSBAS procedure, I selected a different reference point to perform the inversion.
Instead of using the automatic one (selected in step 1-2), I changed the range and azimuth data in the ref12.txt file.
This ref point is in a very coherent region, it is actually a city, that I know is stable.
After step 1-3, I found in the "info" folder a new ref point, 13ref.txt, of course completely different from the one I set.
Why?

**Comment by yumorishita** [comment]
The reference point does not have to be stable in the step13 because the step just calculates the incremental deformation from multiple interferograms. In the step16 where 13ref.txt is used, the reference point still need not to be stable. You would get almost the same result wherever the reference point is selected if the unwrapped data exist in all interferograms and loop phases are small. Only the reference point after step16 affects the result (corresponding to the reference point of PS processing). You don't need to manually select the stable reference point before step13 or 16.

**Comment by yumorishita** [comment]
There seem to be no more questions. Let me close this issue.

**Comment by christianbignami** [comment]
fine, thanks!

*****************************************************
Christian Bignami, PhD
Head of Remote Sensing Unit, National Earthquake Observatory
Istituto Nazionale di Geofisica e Vulcanologia
Via di Vigna Murata, 605
00143, Rome, Italy
e-mail: ***@***.***
http://orcid.org/0000-0002-8632-9979
tel.: +39 0651860659

*****************************************************





Il giorno ven 21 mag 2021 alle ore 13:55 Yu Morishita <
***@***.***> ha scritto:

**Comment by RaeGeoffrey** [comment]
sir u mention "(corresponding to the reference point of PS processing)" what is "PS processing" ?
