### ISSUE TITLE
How can update LiCSBAS? Ubuntu

### ISSUE THREAD

**Issue by ederliga07** [yumorishita/LiCSBAS#109]
I already install one version of LiCSBAS but I want to use the new option from LiCSBAS 1.5.11 using gpu for helping the process .It give me an advise to install cupy but i tried different method to do and didn't work.

**Comment by ederliga07** [comment]
![image](https://user-images.githubusercontent.com/60079150/121822724-3736c980-cc66-11eb-953f-52c21f57d949.png)

**Comment by yumorishita** [comment]
Please show me the version of cupy and output of LiCSBAS_check_install.py.

**Comment by ShadiAbdelhadi** [comment]
It seem that shapely and gdal modules can't be installed after Anaconda installation. This is the error message I received 
![Screenshot from 2021-06-17 15-46-06](https://user-images.githubusercontent.com/85242237/122409131-301ffc00-cf83-11eb-8b9b-6e54b2b6832d.png)

**Comment by yumorishita** [comment]
What python version have you installed? If it is the latest (3.9), I would recommend trying <=3.8.

**Comment by ShadiAbdelhadi** [comment]
> What python version have you installed? If it is the latest (3.9), I would recommend trying <=3.8.

I am not exactly sure, how would I possibly check which version I have?

**Comment by ShadiAbdelhadi** [comment]
> What python version have you installed? If it is the latest (3.9), I would recommend trying <=3.8.
I have downloaded anaconda  64-Bit (x86) Installer (544 MB) that is compatible with python 3.8, there was no option to download previous version of anaconda from their website

**Comment by yumorishita** [comment]
You can check the python version by
```python3 -V```

You can downgrade the version to 3.8 by
```conda install python=3.8```

**Comment by ShadiAbdelhadi** [comment]
I have got clear installation of Ubuntu on. Another device so I start from
the beginning, Which anaconda version should I use

**Comment by ederliga07** [comment]
I suggest install all the modules needed from anaconda navigator, in my case this solve all the issues in clean installation.
type: anaconda-navigator
![image](https://user-images.githubusercontent.com/60079150/122652402-4a351800-d104-11eb-8e59-13a09a9d6f22.png)

**Comment by ederliga07** [comment]
@yumorishita hi, excuse me whats wrong with this problem? Before I ran the program normally but now this error appears.
LICSBAS 1.5.11.
![image](https://user-images.githubusercontent.com/60079150/122658225-48814980-d130-11eb-82f3-0a9af035fe00.png)

**Comment by yumorishita** [comment]
Because no loop remains after step11. Increase ifgs or change the thresholds in step11.

**Comment by ShadiAbdelhadi** [comment]
> I suggest install all the modules needed from anaconda navigator, in my case this solve all the issues in clean installation.
> type: anaconda-navigator
> ![image](https://user-images.githubusercontent.com/60079150/122652402-4a351800-d104-11eb-8e59-13a09a9d6f22.png)

I have Anaconda navigator installed but i still can't install gdal and shapely modules, it's stuck like that for an hour yet. Any suggestions?
![Screenshot from 2021-06-20 12-18-37](https://user-images.githubusercontent.com/85242237/122670319-bc1f6700-d1c1-11eb-87b0-b271bc4e44d4.png)

**Comment by yumorishita** [comment]
Have you tried using python 3.8?

**Comment by ShadiAbdelhadi** [comment]
> Have you tried using python 3.8?

Yes I tried and it never installed python 3.8, I receive this iterating error

![Screenshot from 2021-06-21 16-48-02](https://user-images.githubusercontent.com/85242237/122781811-77bec480-d2b0-11eb-84d2-98b11b816da5.pn![Screenshot from 2021-06-21 16-48-02](https://user-images.githubusercontent.com/85242237/122781850-7f7e6900-d2b0-11eb-8e48-66f909426354.png)

**Comment by yumorishita** [comment]
I suggest trying pyenv:
https://github.com/yumorishita/LiCSBAS/wiki/1_Installation#example-4-install-from-anaconda-or-miniconda-without-being-root

**Comment by ShadiAbdelhadi** [comment]
I ran the ### Install pyenv and pyenv-virtualenv list of commands, this is what I received. Was the installation successful? 
![Screenshot from 2021-06-22 11-16-47](https://user-images.githubusercontent.com/85242237/122898993-afc71580-d34b-11eb-8709-82e508bd5c00.png)
![Screenshot from 2021-06-22 11-16-55](https://user-images.githubusercontent.com/85242237/122899011-b48bc980-d34b-11eb-90b6-3a9e8bec3dec.png)
![Screenshot from 2021-06-22 11-17-05](https://user-images.githubusercontent.com/85242237/122899014-b5246000-d34b-11eb-811b-b0947fae8add.png)
![Screenshot from 2021-06-22 11-17-12](https://user-images.githubusercontent.com/85242237/122899018-b5bcf680-d34b-11eb-814c-ef7fe2f532df.png)
I appreciate your cooperation.

**Comment by ShadiAbdelhadi** [comment]
I followed all the steps but at 1.3 to check the installation of LiCSBAS, I got this error message. How may I resolve it? 
![Screenshot from 2021-06-22 11-48-56](https://user-images.githubusercontent.com/85242237/122903745-fe76ae80-d34f-11eb-8a1a-757795e57a89.png)

**Comment by yumorishita** [comment]
Although the pyenv installation failed because you have not installed git (see the message), you seem to have successfully created the virtual environment 'licsbas' with all required modules including gdal. Please try `conda activate licsbas` (as is shown) then run `LiCSBAS_check_install.py`.

**Comment by ShadiAbdelhadi** [comment]
> Although the pyenv installation failed because you have not installed git (see the message), you seem to have successfully created the virtual environment 'licsbas' with all required modules including gdal. Please try `conda activate licsbas` (as is shown) then run `LiCSBAS_check_install.py`.

I know I have been a burden and commenting too much but it's just because it's my first time to use Linux, I really realy am thankful for your help. I hope the time series creation goes smoothly and won't be interrupted because of the missing modules I couldn't install
![Screenshot from 2021-06-25 20-26-57](https://user-images.githubusercontent.com/85242237/123469946-022a5f80-d5f4-11eb-9be7-30564da0f73c.png)

**Comment by yyzzccmg** [comment]
Hello yumorishita
Thank you for the code, but I have probably very easy problem during installation. I am using Windows and i have installed Anaconda with Python 3.8.8. but when i script the `source <my_LiCSBAS_path>/LiCSBAS/bashrc_LiCSBAS.sh` it says source : The term 'source' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ source
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (source:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I have google it and tried many solution there but still getting the same error. Probably it is very very basic thing and i am missing because not good at the coding language. Do you have any suggestion on that?
Thanks in advance

**Comment by yumorishita** [comment]
https://github.com/yumorishita/LiCSBAS/issues/85#issuecomment-863040843

**Comment by Stephen0255** [comment]
Hi Dr. Yumorishta, I've done all the steps to install LiCSBAS through anaconda3 (python=3.8), when I run the LiCSBAS_check_install.py, it shows "PYTHONPATH is not set to LiCSBAS libraby" though the LiCSBAS_io_lib.py is in the LiCSBASPATH/LiCSBAS_lib directory. What's wrong here? I've also checked the LiCSBAS_check_install.py and find that the importlib in anaconda3 is only for python 2.6 rather than python 3.8. How to solve this problem? 
Thanks in advance!

**Comment by yumorishita** [comment]
Have you done `source <your_LiCSBAS_path>/LiCSBAS/bashrc_LiCSBAS.sh`? Check if the LiCSBASPATH/LiCSBAS_lib is included in the PYTHONPATH by `echo $PYTHONPATH`.

**Comment by yumorishita** [comment]
Let me close this issue because there seem to be no more problems.
