### ISSUE TITLE
Cut issues

### ISSUE THREAD

**Issue by Congzhangg** [yumorishita/LiCSBAS#183]
When I use CAGOS correction in steps 0-3, the first time I run it, I run it as shown in the image below and no processing occurs and the statement is not prompted to complete.And then it stops running
![image](https://user-images.githubusercontent.com/112800803/198837309-30e0f597-f543-4443-98cd-cdefa22829c8.png)

I ran the GACOS correction again, prompting a series of messages and a ValueError in the last line, as shown below:
![image](https://user-images.githubusercontent.com/112800803/198836851-569d34bb-e731-4395-bdec-5db055400409.png)

When using CAGOS correction,
 a series of messages and ValueError appear in the last line, as shown below:
![image](https://user-images.githubusercontent.com/112800803/198836868-2c2ffe5d-5b01-403e-abf4-769452d16a2a.png)
When I clipped the UNM data in step 0-5, an error was reported, as shown in the picture below:
![image](https://user-images.githubusercontent.com/112800803/198836907-694c1f66-293b-4f45-b6ba-8192037076e0.png)
May I ask which step is my problem?

**Comment by yumorishita** [comment]
I guess one of the GACOS/*sltd.geo.tif files is incomplete. Please remove the GACOS directory and retry step03. If the processing is stuck again, I suggest using `--n_para 1` because multiprocessing is sometimes stuck.
I also recommend using [batch_LiCSBAS.sh](https://github.com/yumorishita/LiCSBAS/blob/master/batch_LiCSBAS.sh) rather than running each step.
