### ISSUE TITLE
Strange Uplift results in SBAS

### ISSUE THREAD

**Issue by soroushyasini** [yumorishita/LiCSBAS#255]
Hi Mr. Morishita. I implemented 439 interfrograms and corrected them by 121 GACOS data of frame 174A_05598_131313 from 2020 until 2022. After removing DEM and orbital ramp error, the shown subsidence patterns seems alright but there are significant uplifts in the area which we do not expect them according to local and field data. is there any idea to improving the results ? 
I upload some of the results here. I also attached a Profile of the area which has shown uplift significantly.
![vel filt](https://github.com/yumorishita/LiCSBAS/assets/119971742/364bdbab-655c-4494-99e3-858c201679b0)

![network13](https://github.com/yumorishita/LiCSBAS/assets/119971742/9c1f8017-00dc-4308-addd-f8f5b6b4a20b)
![coh_avg](https://github.com/yumorishita/LiCSBAS/assets/119971742/de9a93cd-7e1e-4ec1-aab0-1593fafad03e)
![vstd](https://github.com/yumorishita/LiCSBAS/assets/119971742/d955b07d-3672-4f83-9d52-a57075868d31)
![1](https://github.com/yumorishita/LiCSBAS/assets/119971742/5d4a92b8-fc49-4063-9b5d-817534a07100)

**Comment by yumorishita** [comment]
Where is the unexpected uplift area you mean? Also please show mask_ts.png.

**Comment by Sakina-A** [comment]
Hi Morishita

I would like to ask about the **upward velocity**. According to the results, the upward velocity corresponds very well to buildings (urbanization) in my study area but because the velocity is in mm/year it can`t be explained by an increase in the buildings height (and it`s too good to be a coincidence that a surface rebound because of groundwater accumulation is happening in the exact location of urban areas) so:

1- Is the velocity calculated based on a reference area/points? meaning that if this reference area/points experienced subsidence will this lead to an uplift in areas with the no movement?

2- If the velocity is not calculated based on No.1 above, then how the upward velocity can be explained in terms of how LiCSBAS works?

  

![Study area](https://github.com/yumorishita/LiCSBAS/assets/125351152/67c7ae85-c700-4360-b1b5-5c0911145b29)

![mask_ts](https://github.com/yumorishita/LiCSBAS/assets/125351152/fe95e81a-f5a0-4e16-9f2b-9c094f5bc79b)

**Comment by yumorishita** [comment]
No. 1 is correct.

**Comment by Sakina-A** [comment]
Got it. Am just a little confused about somethings, so please correct me if I'm wrong:

1- The reference point (chosen by LiCSBAS) is the point selected with the least amount of error for the SB network inversion to calculate the velocity. So, is the reference area (black dashed rectangle) also selected in the same way?

2- According to your reply (https://github.com/yumorishita/LiCSBAS/issues/249#issuecomment-1561023883), the reference point is forced to be zero. Hence, how can I find the amount of displacement at this point so that it can be subtracted/added to the rest of the cells to explain the upward velocity? Do I compare it to the actual displacement at the exact point and time?

**Comment by yumorishita** [comment]
1. No, the reference point is selected again in step16. Please read [this](https://progearthplanetsci.springeropen.com/articles/10.1186/s40645-020-00402-7#:~:text=During%20the%20LiCSBAS%20processing).
2. The displacement of the reference point is already subtracted from the rest of the points (that is why the displacement is zero).

**Comment by Sakina-A** [comment]
Thank you for clarifying No.1 
Regarding No2., what I mean is there a way to know the amount of subtraction before it is applied (the amount of displacement at the reference point before it was set to zero)?

**Comment by yumorishita** [comment]
All the displacement is a relative value and the displacement value with no reference has no meaning. Therefore, there is no absolute displacement value at the selected point before selecting the reference point. If you set the reference at another point, you will find the non-zero displacement at the previous reference point.

**Comment by Sakina-A** [comment]
I understand now, thank you. I chose a new reference area based on your explanation and checked its indices and got reasonable results. 

![_Cumulative_Displacement](https://github.com/yumorishita/LiCSBAS/assets/125351152/72652477-b1e2-4234-8446-e1f37d7e71d1)
