### ISSUE TITLE
error with display of time series and displacement data

### ISSUE THREAD

**Issue by RoySreeta** [yumorishita/LiCSBAS#308]
Hello Dr. Yumorishita,
After downgrading the matplotlib to version 3.4.2, I could run the analysis successfully but I'm still stuck with the display of the time series and displacement plot. When I ran the code this is the error that I'm now facing:

LiCSBAS16_filt_ts.py Successfully finished!!

Output: TS_GEOCml1clip/cum_filt.h5

To plot the time-series:
LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &

(licsbas) sreetama@sreetama:~/anaconda3/envs/licsbas/124D_04854_171313$ LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &
[2] 180562
(licsbas) sreetama@sreetama:~/anaconda3/envs/licsbas/124D_04854_171313$ 
LiCSBAS_plot_ts.py ver1.13.4 20210910 Y. Morishita
LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5

Reading TS_GEOCml1clip/cum_filt.h5
Reading TS_GEOCml1clip/cum.h5 as 2nd
Reading TS_GEOCml1clip/results/mask as mask
Reading GEOCml1clip/U.geo
Reading mask
Reading coh_avg
Reading n_unw
Reading vstd
Reading maxTlen
Reading n_gap
Reading stc
Reading n_ifg_noloop
Reading n_loop_err
Reading resid_rms
Reading slc.mli
Reading hgt
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/home/sreetama/LiCSBAS/bin/LiCSBAS_plot_ts.py", line 890, in <module>
    printcoords(lastevent)
  File "/home/sreetama/LiCSBAS/bin/LiCSBAS_plot_ts.py", line 773, in printcoords
    ii = [np.int](http://np.int/)(np.round(event.ydata))
  File "/home/sreetama/anaconda3/envs/licsbas/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`[np.int](http://np.int/)` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `[np.int](http://np.int/)`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

So can you tell me what I should do to resolve this issue of Attribute error?

**Comment by yumorishita** [comment]
Please see https://github.com/yumorishita/LiCSBAS/issues/250#issuecomment-1562850324.

**Comment by RoySreeta** [comment]
Thank you so much. I switched to LiCSBAS2 and it is working fine.

**Comment by MIEMESSI** [comment]
Hello Dr. Yumorishita,I had this problem
(pan) root@LAPTOP-R6PHF274:/home/LiCSBAS2/143A_05651_131313# LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &
[1] 21571
(pan) root@LAPTOP-R6PHF274:/home/LiCSBAS2/143A_05651_131313#
LiCSBAS_plot_ts.py ver1.14.0 20230219 Y. Morishita
LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5

Reading TS_GEOCml1clip/cum_filt.h5
Reading TS_GEOCml1clip/cum.h5 as 2nd
Reading mask
Reading mask
Reading coh_avg
Reading n_unw
Reading vstd
Reading maxTlen
Reading n_gap
Reading stc
Reading n_ifg_noloop
Reading n_loop_err
Reading resid_rms
Reading slc.mli
Reading hgt
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

**Comment by yumorishita** [comment]
https://github.com/NVlabs/instant-ngp/discussions/300

**Comment by MIEMESSI** [comment]
thank you
