### ISSUE TITLE
 LiCSBAS16_filt_ts.py crashes

### ISSUE THREAD

**Issue by sergintav1** [yumorishita/LiCSBAS#31]
Hi 
I use the following comment: 
LiCSBAS16_filt_ts.py -t TS_GEOCml1mask/ -s 4 -y 0.1 -r 1

and it crashes. Here the message:
Create png for increment with 40 parallel processing...

Find stable reference point...
Selected ref: 2847:2848/1756:1757

Calculate velocity of filtered time series...
  First, solving 2929268/3958793th points with full cum...
Segmentation fault (core dumped)

I tried different values. But it crashed in all of them.

P.S: my frame ıd is 036D_04976_131313
Thanks a lot

**Comment by yumorishita** [comment]
It is strange. I cannot reproduce the error. It might be because of your environment. Could you try:

1. replacing the script with old v1.2 below and rerun https://raw.githubusercontent.com/yumorishita/LiCSBAS/5315f0e3365b42f43066ff209df04eab67b09ee9/bin/LiCSBAS16_filt_ts.py

2. changing to nlook="10" in batch_LiCSBAS.sh and reprocessing from step11

**Comment by sergintav1** [comment]
I re-created my conda environment and I solved the problem. Thanks for your fast response.

**Comment by alejobeap** [comment]
Dear 
I saw in the step 1-16 in the wiki part that is possible plot the elevation vs displacement ? which folder has this file ?? Thanks
Alejandro

**Comment by yumorishita** [comment]
When you use --hgt_linear option (p16_hgt_linear="y" in batch_LiCSBAS.sh), the plots are created in 16filt_cum and 16filt_increment.
