### ISSUE TITLE
How can I filter out winter-acquired images and execute LiCSBAS for multiple years?

### ISSUE THREAD

**Issue by amrit-thapa-2044** [yumorishita/LiCSBAS#337]
Due to the heavy snowfall in my region during winter, I'm considering excluding images from that season and conducting InSAR time series analysis over several years. Can LiCSBAS accommodate this? I'm concerned that removing winter images might disrupt the time series. Is there a method within LiCSBAS to address this issue?

**Comment by yumorishita** [comment]
You can exclude the winter data from the LiCSBAS processing by removing the winter pair `yyyymmdd_yyyymmdd` directories from the GEOC directory. LiCSBAS cannot fill the gap of the time series in winter because it just uses the prepared interferograms. If you want to fill the gap in winter, you need to produce the interferograms spanning winter yourself.
