### ISSUE TITLE
Does LiCSBAS run on Mac OS?

### ISSUE THREAD

**Issue by Pirog3266** [yumorishita/LiCSBAS#35]
I might install LiCSBAS on Mac because LiCSBAS_check_install.py  showed O.K.to all checking list.
When I run, It might works halfway but after that, it showed like this
-------- ----------------------------------------------------------------------------------------------
LiCSBAS02_ml_prep.py ver1.7.1 20201028 Y. Morishita
LiCSBAS02_ml_prep.py -i GEOC -n 1

Create E.geo
  E.geo created

Create N.geo
  N.geo created

Create U.geo
  U.geo created

Create slc.mli
  No *.geo.mli.tif found in GEOC

Create hgt
  hgt[.png] created

Create unw and cc
  4 parallel processing...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/inakura_imac/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 389, in convert_wrapper
    ifgd = ifgdates2[i]
NameError: name 'ifgdates2' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/inakura_imac/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 449, in <module>
    sys.exit(main())
  File "/Users/inakura_imac/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 284, in main
    rc = p.map(convert_wrapper, range(n_ifg2))
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
NameError: name 'ifgdates2' is not defined
-------------------------------------------------------------------------------------------------------------

**Comment by yumorishita** [comment]
I have got the same issue report in Mac personally. Probably the error is caused by the changed default setting of multiprocessing in Mac python >=3.8.
https://www.tsuyukimakoto.com/blog/2019/12/10/multiprocessing_and_global_variable/
https://docs.python.org/ja/3/library/multiprocessing.html#contexts-and-start-methods

Could you try inserting a line `multi.set_start_method('fork')` just after the line
https://github.com/yumorishita/LiCSBAS/blob/281fa775b6d9b1ac6472868ddde6a8f607dc5173/bin/LiCSBAS02_ml_prep.py#L89
and re-running LiCSBAS (though the same error will occur in later steps)?

If it works I will update the modules.

**Comment by Pirog3266** [comment]
Same errors occurred on

LiCSBAS05op_clip_unw.py
LiCSBAS12_loop_closure.py
LiCSBAS13_sb_inv.py
LiCSBAS16_filt_ts.py

So, when I inserted the line told by you,
LiCSBAS run completly !!
Thanks !

**Comment by yumorishita** [comment]
I have updated all scripts which use multiprocessing. Thank you for the feedback.
