### ISSUE TITLE
A question about the result

### ISSUE THREAD

**Issue by kedaxu1** [yumorishita/LiCSBAS#54]
Dear Morishita

Thanks for sharing LiCSBAS, I met a issue when I use it, hope can get some help.

In my result ,we also can find a trends related to terrain or atmosphere, and I have set the parameters --hgt_linear and p16_deg_deramp="1". Especially in large-area applications, this trend is more obvious in applications with a range of 250km.
Can you give me some suggestions? Thanks for your help.

![_Cumulative_Displacement](https://user-images.githubusercontent.com/74855593/103597438-2eb1c880-4f3b-11eb-9530-0206995ca929.png)

[202101041018batch_LiCSBAS_02_16.log](https://github.com/yumorishita/LiCSBAS/files/5767630/202101041018batch_LiCSBAS_02_16.log)

![_Cumulative_Displacement1](https://user-images.githubusercontent.com/74855593/103597597-9d8f2180-4f3b-11eb-8ac5-d910626ee8b8.png)

**Comment by yumorishita** [comment]
I am not sure what you mean by trend. Perhaps topography-correlated signals? First please check 16filt_cum/*_hgt_linear.png and 16filt_cum/*_hgt_corr.png to confirm the hgt_linear correction worked well.

The signals might be systematic bias caused by fading signals (please read a paper https://ieeexplore.ieee.org/document/9130052). Currently there is no way to mitigate the bias in LiCSBAS.

**Comment by kedaxu1** [comment]
Thanks for your quist answer. I have check the 16filt_cum/_hgt_linear.png and 16filt_cum/_hgt_corr.png and the hgt_linear correction worked well. But the result also have some topography-correlated signals, that is systematic bias caused by fading signals?

In LiCSBAS_plot_ts.py I change the ref area by right-drag, and how to save the result after change ref area?

Thanks for your help!

![16filt_cum_hgt_corr png](https://user-images.githubusercontent.com/74855593/103608493-709c3800-4f56-11eb-884a-bec7e11e1c7c.png)

![_Cumulative_Displacement1](https://user-images.githubusercontent.com/74855593/103608512-7abe3680-4f56-11eb-955e-c392506b216d.png)

**Comment by yumorishita** [comment]
Currently we cannot confirm the topography-correlated signals are caused by the fading signals. The systematic bias correlate with land use. I suggest compare the velocity with the land use.

The redefined reference area cannot be saved, but you can set the reference area with -r or --ref_geo options in the initial view.

**Comment by kedaxu1** [comment]
Thanks for your patient help.
