### ISSUE TITLE
Mask Noisy Pixels at Step 1-5

### ISSUE THREAD

**Issue by fangjinSGG** [yumorishita/LiCSBAS#59]
At step 1-5, I need to keep a large threshold, e.g., n_loop_err (10 or even larger), resid_rms (2.5 or larger), to obtain a good mask. What are the specific criteria for this step?  I would be very grateful for any suggestions you could give me.

**Comment by yumorishita** [comment]
These thresholds are case-by-case and there are no specific criteria. Generally, you may set large n_loop_err if the number of available ifgs is large. Larger thresholds mean lower accuracy. If deformation of interest is quite large, you may use large thresholds because the error would be relatively small compared with the deformation.

**Comment by fangjinSGG** [comment]
I have masked pixels with low coherence (≤ 0.1). It should have improved the loop closure in the case of many unwrapping errors. I was wondering why some pixels have quite larger loop errors than other pixels.

**Comment by yumorishita** [comment]
The reason why some pixels have large loop errors is that they have unwrapping errors. I may not understand what you mean by pixels with large loop errors.

**Comment by fangjinSGG** [comment]
In terms of the n_loop_err, some pixels have a larger value than others.

**Comment by yumorishita** [comment]
OK. Does my response answer your question, or do you still have unclear points?
