### ISSUE TITLE
Step LiCSBAS13 problem

### ISSUE THREAD

**Issue by bondangd45** [yumorishita/LiCSBAS#6]
Dear Prof Yu,

I was installing the LiCSBAS on Ubuntu 16.04 by using Anaconda3. I have tried to follow the steps, but I could not install the gdal module by using: conda install gdal, directly. Then I tried to use that command line after I created the conda virtual environment. In here, I can use the gdal. But I also have to install the other modules including astropy, beautifulsoup4, matplotlib, h5py, numpy, requests, and statsmodels because I cannot use the modules directly from /home.
My steps is as follows:
1. Install the Anaconda in /home. Python version detected is Python 3.8.2
2. install the Anaconda environment by using: conda create --name myenv. Then I activate it.
3. In the Anaconda environment, I also install the modules required for LiCSBAS process
4. cd <your_LiCSBAS_path>
    git clone https://github.com/yumorishita/LiCSBAS.git
4. Make the directory which is used for the LiCSBAS processing
5. source <your_LiCSBAS_path>/LiCSBAS/bashrc_LiCSBAS.sh
6. setting the batch file and then run it by using: ./batch_LiCSBAS.sh

Then, I found the problem in the following text:
LiCSBAS13_sb_inv.py ver1.2 20200225 Y. Morishita
LiCSBAS13_sb_inv.py -d GEOCml1clip
In geographical coordinates

Size of image (w,l)    : 202, 242
# of all images        : 3
# of images to be used : 3
# of all ifgs          : 3
# of ifgs to be used   : 3
# of removed ifgs      : 0
Threshold of used unw  : 3

Reference area (X/Y)   : 194:195/193:194
Allowed memory size    : 4000 MB
Number of patches      : 1
Inversion algorism     : LS
Gamma value            : 0.0001

Process 242/242th line (1/1th patch)...
  Reading 3 ifg's unw data...
  48884/48884 points removed due to not enough ifg data...

  Identifing gaps and counting n_gap...
  Counting n_ifg_noloop...

  Small Baseline inversion by LS...

  Next, solve 0 points including nan point-by-point...

  Elapsed time for 1th patch: 00h 00m 00s

Find stable reference point...
/home/bondan/anaconda3/envs/myenv/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1115: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,
/home/bondan/LiCSBAS/LiCSBAS/bin/LiCSBAS13_sb_inv.py:628: RuntimeWarning: All-NaN slice encountered
  min_n_gap = np.nanmin(n_gap)
/home/bondan/LiCSBAS/LiCSBAS/bin/LiCSBAS13_sb_inv.py:634: RuntimeWarning: All-NaN slice encountered
  min_rms = np.nanmin(rms_cum_wrt_med)
Traceback (most recent call last):
  File "/home/bondan/LiCSBAS/LiCSBAS/bin/LiCSBAS13_sb_inv.py", line 753, in <module>
    sys.exit(main())
  File "/home/bondan/LiCSBAS/LiCSBAS/bin/LiCSBAS13_sb_inv.py", line 636, in main
    refy1s, refx1s = refy1s[0], refx1s[0] ## Only first index
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by yumorishita** [comment]
The reason of the error is that the number of ifgs is too small (only 3) to carry out the time series analysis. What is your frame ID? Firstly the sufficient number of ifgs must be created and published. You can request processing of your frame ID of interest on LiCSAR portal (https://comet.nerc.ac.uk/COMET-LiCS-portal/, right column).

**Comment by bondangd45** [comment]
Okay Prof, I will try to use longer period. The frame ID is: 076D_09725_121107. 
Actually I also this problem when I try to process in another frame ID, Prof. The frame ID is 119D_09370_100707.

**Comment by sazzath** [comment]
Are there any videos for installation for LiCSBAS ??? One video can solve 100 Problems !!

**Comment by yumorishita** [comment]
Sorry, there is no videos. The installation of LiCSBAS itself is very easy as is written in [wiki](https://github.com/yumorishita/LiCSBAS/wiki/1_Installation#12-licsbas-module), while setup of a python environment is complicated for users who are not familiar with python. It is difficult to show a general method to setup a python environment because every user has different situations. Plenty of information of python is available on the internet. Please google it.

**Comment by sazzath** [comment]
Is this linux base tools ?

**Comment by yumorishita** [comment]
Yes, but should work on Mac or Windows as well. LiCSBAS needs Python and bash. If you don't have a linux, I recommend using VMware to use linux on Windows.

**Comment by irmayolii2** [comment]
Hi Prof Yu
Why when I try to display timeseries with script "LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &"
it's error like this

![Uploading WhatsApp Image 2021-09-09 at 21.46.21.jpeg…]()

**Comment by irmayolii2** [comment]
Hi Prof Yu
Why when I try to display timeseries with script "LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &"
it's error like this.

***script to display timeseries***
112A_09051_071616$ LiCSBAS_plot_ts.py -i TS_GEOCml1maskclip/cum_filt.h5 &

***result***
[1] 24466
LiCSBAS_2/LiCSBAS/112A_09051_071616$
LiCSBAS_plot_ts.py ver1.13.3 20210205 Y. Morishita
LiCSBAS_plot_ts.py -i TS_GEOCml1maskclip/cum_filt.h5

Reading TS_GEOCml1maskclip/cum_filt.h5
Traceback (most recent call last):
  File "/media/geodesi/SSD_2TB/skripsi_irma/LiCSBAS_2/LiCSBAS/bin/LiCSBAS_plot_ts.py", line 361, in <module>
    refx1, refx2, refy1, refy2 = [int(s) for s in re.split('[:/]', refarea)]
  File "/home/geodesi/miniconda3/envs/licsbas/lib/python3.8/re.py", line 231, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by yumorishita** [comment]
Although I cannot reproduce this error in my environment, I have modified the codes to avoid it because the error reports have been increasing.
https://github.com/yumorishita/LiCSBAS/commit/7637465c7b8687ea2910954246452d9cf946c96a

Please update the LiCSBAS module and try again.

**Comment by IamTariqAshraf** [comment]
Have a nice day. I wanted to ask if i have used gamma for preprocessing like making interferograms and unwrapp files can i use LICSBAS for visulaization only?

**Comment by yumorishita** [comment]
Yes, you can use [LiCSBAS_disp_img.py](https://github.com/yumorishita/LiCSBAS/blob/master/bin/LiCSBAS_disp_img.py) to display the gamma files.

**Comment by IamTariqAshraf** [comment]
Wow it's a good news thank you so much for your kind response sir 
---- Replied Message ----
From Yu Morishita ***@***.***> Date 08/02/2023 21:47 To yumorishita/LiCSBAS ***@***.***> Cc Tariq Ashraf ***@***.***>,
Comment ***@***.***> Subject Re: [yumorishita/LiCSBAS] Step LiCSBAS13 problem (#6)  

Yes, you can use LiCSBAS_disp_img.py to display the gamma files.

**Comment by IamTariqAshraf** [comment]
Dear Sir, Yumorishita, Thank you so much for your kind response. Sorry to bother you again but can we do some thing more or we can only visualize the gamma processed data using LiCSBAS. I mean like plotting time series using LiCSBAS_plot_ts.py ?

**Comment by yumorishita** [comment]
Technically it is possible to create .h5 from any format but I have no tool to convert gamma time series results to .h5. You should make it yourself if you want to use LiCSBAS_plot_ts.py.

**Comment by IamTariqAshraf** [comment]
Mr.Yumorishita , Thank you for your kind response

**Comment by nadiaaurora** [comment]
Hi Prof Yu,
 I’m currently processing InSAR data using LiCSBAS and encountered an error in Step 13 (sb_inv). Below is the information about my setup and the full error log.


Size of image (w,l)    : 2718, 2780
# of all images        : 182
# of images to be used : 33
# of all ifgs          : 906
# of ifgs to be used   : 26
# of removed ifgs      : 880
Threshold of used unw  : 33

Reference area (X/Y)   : 1556:1557/2464:2465
Allowed memory size    : 8000 MB
Number of patches      : 1
Inversion algorism     : LS
Gamma value            : 0.0001

Process 2780/2780th line (1/1th patch)...
  Reading 26 ifg's unw data...
  7556040/7556040 points removed due to not enough ifg data...
  Elapsed time for 1th patch: 00h 00m 03s

Find stable reference point...
/home/nadsaf22/LiCSBAS2/bin/LiCSBAS13_sb_inv.py:726: RuntimeWarning: All-NaN slice encountered
  sumsq_cum_wrt_med = sumsq_cum_wrt_med + (cum[i, :, :]-np.nanmedian(cum[i, :, :]))**2
/home/nadsaf22/LiCSBAS2/bin/LiCSBAS13_sb_inv.py:731: RuntimeWarning: All-NaN slice encountered
  min_n_gap = np.nanmin(n_gap)
/home/nadsaf22/LiCSBAS2/bin/LiCSBAS13_sb_inv.py:737: RuntimeWarning: All-NaN slice encountered
  min_rms = np.nanmin(rms_cum_wrt_med)
Traceback (most recent call last):
  File "/home/nadsaf22/LiCSBAS2/bin/LiCSBAS13_sb_inv.py", line 951, in <module>
    sys.exit(main())
  File "/home/nadsaf22/LiCSBAS2/bin/LiCSBAS13_sb_inv.py", line 739, in main
    refy1s, refx1s = refy1s[0], refx1s[0] ## Only first index
IndexError: index 0 is out of bounds for axis 0 with size 0


It seems the reference point selection fails because all candidates are NaN. The Frame ID is 018D_09287_131313
Do you have any suggestions on what might be causing this issue or how to fix it?

Thank you very much for your help.

**Comment by nadiaaurora** [comment]
Additionally, how many interferograms are minimally required for a stable time-series analysis in LiCSBAS?
