### ISSUE TITLE
Error in plotting (related with SCM Module)

### ISSUE THREAD

**Issue by firmanhadi** [yumorishita/LiCSBAS#61]
Dear all,

I have installed LiCSBAS previously in Ubuntu and Windows without any problem.
Currently, I am using macOS Big Sur on MBP M1 (Apple Silicon). 
I installed LiCSBAS in a Homebrew environment. 
I couldn't plot the result from the previous works done in Ubuntu.
The error message was 
`ModuleNotFoundError: No module named 'SCM'`

I tried to install SCM with pip but couldn't find one.

I would like to request if anyone had found the problem and got solution.
Thanks a lot.

Regards,

Firman.

**Comment by yumorishita** [comment]
Since SCM is included in the LiCSBAS package (https://github.com/yumorishita/LiCSBAS/tree/master/LiCSBAS_lib/SCM), you need not install it.

I am not familiar with Mac, but please type
`echo $PYTHONPATH`
and check if `*/LiCSBAS/LiCSBAS_lib` is included in the output. If not, you may have not done `source <your_LiCSBAS_path>/LiCSBAS/bashrc_LiCSBAS.sh`.

**Comment by firmanhadi** [comment]
Dear Yu,

Thank you very much for your prompt reply.
It works now, as I forgot to do the last step as you mentioned (`source <your_LiCSBAS_path>/LiCSBAS/bashrc_LiCSBAS.sh `).

Huge thanks.

Cheers, 
Firman.
