### ISSUE TITLE
BAD OBJECTS 

### ISSUE THREAD

**Issue by sazzath** [yumorishita/LiCSBAS#82]
![image](https://user-images.githubusercontent.com/72601348/108849790-dd40c400-75e2-11eb-9b13-935083255ecc.png)
[202102210449batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/6029123/202102210449batch_LiCSBAS_01_16.log)

**Comment by sazzath** [comment]
![image](https://user-images.githubusercontent.com/72601348/108853338-e5026780-75e6-11eb-938c-a7f53a70730d.png)

**Comment by yumorishita** [comment]
The cum_filt.h5 file seems to be corrupted. According to the log, step16 did not finish. Please run step16 again.

**Comment by sazzath** [comment]
![image](https://user-images.githubusercontent.com/72601348/108987491-a5458980-7693-11eb-9cd1-c96e89407c73.png)
Why I am not getting the same result for you done in PDF :    124D_04854_171313   
x-special/nautilus-clipboard
copy
file:///home/sazzath/SAM/LiCSBAS/124D_04854_171313/log/202102231431batch_LiCSBAS_sample_CF_01_16.log

**Comment by yumorishita** [comment]
You can set the start and end steps in the batch script:
https://github.com/yumorishita/LiCSBAS/blob/db454df4220a3dbc30ca092102fa3151dff560b9/batch_LiCSBAS.sh#L19
https://github.com/yumorishita/LiCSBAS/blob/db454df4220a3dbc30ca092102fa3151dff560b9/batch_LiCSBAS.sh#L20

"Elapsed time" and "Successfully finished!!" messages are displayed and logged when each step is successfully finished. Please see the log file.

The difference is because you select the different reference area and point.

**Comment by sazzath** [comment]
Hello Sir , 
![Screenshot from 2021-02-25 14-27-04](https://user-images.githubusercontent.com/72601348/109160191-c7afd380-7775-11eb-8ecb-bcc2b866d273.png)

This time series is yours, I got it from your PDF file, But I select exactly the same point and the area but the out put is not the same. 

I already put my output above. So you can differentiate it. 

Please Help m out

**Comment by yumorishita** [comment]
It is natural that the result is different because new data (in 2018) have been added since I created the PDF and you use them.

You are not selecting exactly the same point and the area. Also you must run LiCSBAS_plot_ts.py in a TS_GEOCml* directory.

Try in a TS_GEOCml*:
`LiCSBAS_plot_ts.py -r 84:116/2:26 -p 107/83 &`

The left double click should work. If not, the problem is in your environment and I cannot help you.
